### ISSUE TITLE
missing .ogg files for airports on various maps

### ISSUE THREAD

**Issue by DarthZyll** [FlightControl-Master/MOOSE_SOUND#4]
audited the existing files in MOOSE_SOUND/ATIS/ATIS Soundfiles/ under the corresponding maps, against the list of airbase names in Wrapper.Airbase. these are the .ogg files that need to be generated:

PersianGulf
  Quasoura_airport.ogg

TheChannel
  Biggin Hill.ogg
  Eastchurch.ogg
  Headcorn.ogg

MarianaIslands
  Olf Orote.ogg
  Pagan Airstrip.ogg

SouthAtlantic
  *.ogg

Sinai
  Sde Dov.ogg

**Comment by Applevangelist** [comment]
Done
